packages <- c("shiny",
              "bcrypt",
              "DBI",
              "dplyr",
              "DT",
              "ggplot2",
              "ggraph",
              "ggrepel",
              "ggridges",
              "igraph",
              "networkD3",
              "plotly",
              "pool",
              "purrr",
              "RSQLite",
              "shinyFeedback",
              "tidyr",
              "UpSetR")

install.packages(packages)
